# Generated by Django 4.1.3 on 2023-01-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_buku', models.ImageField(null = True, blank = True, upload_to='cover')),
                ('judul', models.CharField(max_length=255)),
                ('penulis', models.CharField(max_length=50)),
                ('penerbit', models.CharField(max_length=50)),
                ('tahun_terbit', models.IntegerField(max_length=4)),
                ('sinopsis', models.TextField()),
                
            ],
        ),
    ]
