# Generated by Django 4.1.3 on 2023-01-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='waktu_posting',
            field=models.DateTimeField(auto_now_add=True, default='exit'),
            preserve_default=False,
        ),
    ]
