# Generated by Django 4.1.3 on 2023-01-12 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0002_post_waktu_posting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='waktu_posting',
        ),
    ]
