# Generated by Django 4.1.3 on 2023-01-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0003_remove_post_waktu_posting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_buku',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='penerbit',
            field=models.DateField(),
        ),
    ]
