# Generated by Django 4.1.3 on 2023-01-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0004_alter_post_cover_buku_alter_post_penerbit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='penerbit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='tahun_terbit',
            field=models.IntegerField(),
        ),
    ]
