# Generated by Django 4.1.3 on 2023-01-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0005_alter_post_penerbit_alter_post_tahun_terbit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_buku',
        ),
    ]
