# Generated by Django 4.1.3 on 2023-01-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0006_remove_post_cover_buku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=255)),
                ('buku', models.CharField(max_length=50)),
                ('tgl_pinjam', models.DateField()),
                ('tgl_kembali', models.DateField()),
            ],
        ),
    ]
