# Generated by Django 4.1.3 on 2023-01-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0007_tamu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tamu',
        ),
    ]
