# Generated by Django 4.1.3 on 2023-01-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0009_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='tgl_kembali',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='guest',
            name='tgl_pinjam',
            field=models.IntegerField(),
        ),
    ]
