# Generated by Django 4.1.3 on 2023-01-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0011_alter_guest_tgl_kembali_alter_guest_tgl_pinjam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='tgl_kembali',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='tgl_pinjam',
        ),
    ]
